trigger:
  branches:
    include:
      - release/*
      - hotfix/*

pr:
  branches:
    include:
      - release/*
      - hotfix/*

stages:
  - stage: ValidateBranch
    displayName: "Validate Branch"
    jobs:
      - job: CheckBranch
        displayName: "Check Branch Compatibility"
        steps:
          - script: |
              echo "Validating branch..."
              if [[ ! $(Build.SourceBranch) =~ ^refs/heads/(release|hotfix)/ ]]; then
                echo "Error: Pipeline can only run on 'release/*' or 'hotfix/*' branches."
                exit 1
              fi
            displayName: "Validate if branch is allowed"

  - stage: Deploy
    displayName: "Deployment"
    dependsOn: ValidateBranch
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: "Deploy Job"
        steps:
          - script: echo "Deploying to environment..."
            displayName: "Deploy Step"

